spring:
  application:
    name: dp-data-asset
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_DATABASE_DB1_USERNAME:root}
    password: ${MYSQL_DATABASE_DB1_PASSWORD:123456}
    url: jdbc:mysql://${MYSQL_DATABASE_DB1_HOST_WRITE:localhost}:${MYSQL_DATABASE_DB1_PORT:3306}/${MYSQL_DATABASE_DB1_NAME:idg}?useUnicode=true&characterEncoding=UTF-8&useSSL=true&verifyServerCertificate=false
    #username: root
    #password: 123456
    #url: jdbc:mysql://localhost:3306/idg?useUnicode=true&characterEncoding=UTF-8&useSSL=true&verifyServerCertificate=false
    type: com.alibaba.druid.pool.DruidDataSource
  liquibase:
    change-log: classpath:changelog/changelog.sql
    enabled: true
    clear-checksums: true
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB

server:
  port: 80

mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

